language: common-lisp
sudo: false

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=ecl

matrix:
  allow_failures:
    - env: LISP=ecl

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

script:
  - ros -s fiveam -e '(ql:quickload :cl-cooperative)
                      (asdf:test-system :cl-cooperative)'

